language: node_js
node_js:
  - "stable"
cache:
  directories:
  - webapp/node_modules
  
install:
  - npm install --prefix webapp
  
script:
  - npm test --prefix webapp --passWithNoTests
  - npm run test:coverage --prefix webapp --passWithNoTests
  - npm run build --prefix webapp
